project:
  type: book
  output-dir: docs

book:
  title: "Análisis de series de tiempo"
  author: "Julieta Ruiz, Andrés García, Sofía Bello"
  chapters:
    - index.qmd
    - "Descriptivo Dian (2).qmd"
    - "Descriptivo Energia.qmd"

bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

editor: visual

lang: es
