project:
  type: book
  output-dir: docs

book:
  title: "Análisis de series de tiempo"
  author: "Julieta Ruiz Castiblanco, Andrés Gracía López, Sofía Bello Dueñas"
  chapters:
    - index.qmd
    - "Descriptivo Dian.qmd"
    - "Descriptivo Energia.qmd"
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

lang: es
